### ISSUE TITLE
Learn Ticket

### ISSUE THREAD

**Issue by junichi-mori** [Shaxware/test#2]

**Comment by junichi-mori** [comment]
test

**Comment by hidori** [comment]
@junichi-mori これまだ必要？ 要らないならクローズしてちょ

**Comment by junichi-mori** [comment]
ステータスの変え方で、教えて下さい。
waffle.ioで、このIssueのステータスを変えようとすると
"Only collaborators can update cards"
というメッセージが出て変更出来ないです。
Assigned,Labelsを変更するリンクも出てこないですね。
何か設定が足らないでしょうか？
ちなみに、GitHubでもほぼ同じ状況ですが、closeのボタンは出ています。

**Comment by junichi-mori** [comment]
@hidori メンション送ります

**Comment by hidori** [comment]
@junichi-mori このレポジトリと waffle.io の紐づけが出来てないからと思われます。
関連付けには、レポジトリの管理者権限が必要です。
紐づけの話は、Fixer のオフィスでセ詰めしましたよね？

**Comment by hidori** [comment]
あと、waffle.io は細かいバグが多いので、何か問題が起きたらブラウザでリロードかけて、もう一度試してみてください。

**Comment by hidori** [comment]
@junichi-mori 
>ちなみに、GitHubでもほぼ同じ状況ですが、closeのボタンは出ています。

Assign 変更やラベルのつけ外しが出来ない感じですか？？
それは。。極端にアクセス権限が低すぎるような。。
今日は午後から出社になりますが、出社したら画面見せてください。
Fixer のレポジトリではそんな現象起きてないですよね？

**Comment by junichi-mori** [comment]
ありがとうございました。Assignとかラベルの設定が出来ました。
なお、Fixerでは起きていません。

**Comment by hidori** [comment]
:+1:
